services:
  caddy:
    container_name: caddy
    image: docker.io/library/caddy:2-alpine
    network_mode: host
    restart: unless-stopped
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy-data:/data:rw
      - caddy-config:/config:rw
    environment:
      SEARXNG_HOSTNAME: "${SEARXNG_HOSTNAME:-http://localhost}"
      SEARXNG_TLS: "${LETSENCRYPT_EMAIL:-internal}"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

  redis:
    container_name: redis
    image: docker.io/valkey/valkey:8-alpine
    command: valkey-server --save 30 1 --loglevel warning
    restart: unless-stopped
    networks:
      - local_ai_rig
    volumes:
      - valkey-data2:/data
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

  searxng:
    container_name: searxng
    image: docker.io/searxng/searxng:latest
    restart: unless-stopped
    networks:
      - local_ai_rig
    volumes:
      - ./searxng:/etc/searxng:rw
    environment:
      SEARXNG_BASE_URL: "https://${SEARXNG_HOSTNAME:-localhost}/"
      UWSGI_WORKERS: "${SEARXNG_UWSGI_WORKERS:-4}"
      UWSGI_THREADS: "${SEARXNG_UWSGI_THREADS:-4}"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

  open-webui:
    container_name: open-webui
    image: ghcr.io/open-webui/open-webui:main
    networks:
      - local_ai_rig
    ports:
      - 8080:8080/tcp
    environment:
      OLLAMA_BASE_URL: "http://ollama:11434"
      WEBUI_AUTH: False
      ENABLE_WEB_SEARCH: True
      WEB_SEARCH_ENGINE: "searxng"
      WEB_SEARCH_RESULT_COUNT: 5
      WEB_SEARCH_CONCURRENT_REQUESTS: 20
      SEARXNG_QUERY_URL: "http://searxng:8080/search?q=<query>"
    volumes:
      - open-webui-data:/app/backend/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - ollama

  ollama:
    container_name: ollama
    image: ollama/ollama:rocm
    networks:
      - local_ai_rig
    ports:
      - 11434:11434/tcp
    environment:
      OLLAMA_HOST: "0.0.0.0:11434"
    volumes:
      - ollama-data:/root/.ollama
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    devices:
      - /dev/kfd
      - /dev/dri


networks:
  local_ai_rig:

volumes:
  caddy-data:
    name: caddy-data
  caddy-config:
    name: caddy-config
  valkey-data2:
    name: valkey-data2
  open-webui-data:
    name: open-webui-data
  ollama-data:
    name: ollama-data